name: Build iOS Unsigned IPA

on:
  workflow_dispatch:

permissions: write-all

jobs:
  ios-unsigned-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm i

      - name: Build Frontend Static Assets
        run: pnpm build

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Init Tauri iOS
        run: pnpm tauri ios init || echo "iOS platform already initialized"

      - name: Copy frontend build into Xcode project
        run: |
          rm -rf src-tauri/gen/apple/App/Resources/*
          cp -r build/* src-tauri/gen/apple/App/Resources/

      - name: Patch Xcode project to disable signing
        run: |
          PBXPROJ="src-tauri/gen/apple/app.xcodeproj/project.pbxproj"
          sed 's/DEVELOPMENT_TEAM = .*/DEVELOPMENT_TEAM = "";/g' "$PBXPROJ" > "$PBXPROJ.tmp" && mv "$PBXPROJ.tmp" "$PBXPROJ"
          sed 's/CODE_SIGNING_REQUIRED = YES;/CODE_SIGNING_REQUIRED = NO;/g' "$PBXPROJ" > "$PBXPROJ.tmp" && mv "$PBXPROJ.tmp" "$PBXPROJ"
          sed 's/CODE_SIGNING_ALLOWED = YES;/CODE_SIGNING_ALLOWED = NO;/g' "$PBXPROJ" > "$PBXPROJ.tmp" && mv "$PBXPROJ.tmp" "$PBXPROJ"

      - name: Build iOS Debug IPA (Unsigned)
        run: |
          xcodebuild \
            -workspace src-tauri/gen/apple/app.xcodeproj/project.xcworkspace \
            -scheme app_iOS \
            -configuration Debug \
            -sdk iphoneos \
            BUILD_DIR=build/ios \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            DEVELOPMENT_TEAM=""

      - name: Package IPA
        run: |
          APP_PATH=$(find build/ios/Debug-iphoneos -name "*.app" -type d | head -n 1)
          if [ -z "$APP_PATH" ]; then
            echo "Error: .app not found!"
            exit 1
          fi
          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          IPA_NAME="spend-what-ios-unsigned-${GITHUB_RUN_ID}.ipa"
          zip -r "$IPA_NAME" Payload
          rm -rf Payload
          echo "IPA_NAME=$IPA_NAME" >> $GITHUB_ENV

      - name: Upload IPA to GitHub Release
        uses: softprops/action-gh-release@
