name: Build Tauri iOS (Unsigned)

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1. 获取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Rust
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # 3. 安装 Tauri CLI
      - name: Install Tauri CLI
        run: cargo install tauri-cli --force

      # 4. 安装 Node.js（fnm 管理）并安装依赖
      - name: Setup Node.js and dependencies
        run: |
          curl -fsSL https://fnm.vercel.app/install | bash
          export PATH="$HOME/.fnm:$PATH"
          fnm install --lts
          fnm use --lts
          npm ci

      # 5. 安装 CocoaPods
      - name: Install CocoaPods
        run: brew install cocoapods

      # 6. 构建 Tauri App
      - name: Build Tauri App
        run: npm run tauri build

      # 7. 自动生成 ExportOptions.plist
      - name: Generate ExportOptions.plist
        run: |
          cat <<EOF > src-tauri/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>compileBitcode</key>
            <false/>
            <key>destination</key>
            <string>export</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>teamID</key>
            <string></string>
          </dict>
          </plist>
          EOF

      # 8. 构建 iOS 未签名 app
      - name: Build iOS unsigned IPA
        run: |
          cd src-tauri/target/release/bundle
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Debug \
            -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO \
            BUILD_DIR=build/ios \
            clean build

      # 9. 打包 IPA（未签名）
      - name: Archive IPA
        run: |
          cd src-tauri/target/release/bundle/build/ios
          mkdir -p ipa
          xcodebuild -exportArchive \
            -archivePath Runner.xcarchive \
            -exportOptionsPlist ../../ExportOptions.plist \
            -exportPath ./ipa || echo "Unsigned IPA created"

      # 10. 上传 IPA 作为 artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: tauri-ios-unsigned
          path: src-tauri/target/release/bundle/build/ios/ipa
