name: Release Build

on:
  workflow_dispatch:

permissions: write-all

jobs:
  create-release-for-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: false 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Pnpm install
        run: pnpm i

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Tauri iOS without signing
        run: |
          export RUST_LOG=info
          pnpm tauri ios build --verbose -- \
            CODE_SIGNING_ALLOWED="NO" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED="NO" \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

      - name: Package IPA (Unsigned)
        run: |
          APP_PATH=$(find src-tauri/gen/apple/ -name "*.app" -type d | head -n 1)
          echo "App found at $APP_PATH"
          mkdir -p Payload
          cp -r "$APP_PATH" Payload/
          zip -r spend-what-${GITHUB_REF##*/}-ios-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: Spend What ${GITHUB_REF##*/} iOS Unsigned
          tag_name: ${{ github.ref_name }}
          files: |
            spend-what-${GITHUB_REF##*/}-ios-unsigned.ipa
