name: Release Build

on:
  # git tag 触发。
  push:
    tags:
      - "v*.*.*"

permissions: write-all

jobs:
  check_tag_version:
    name: Check Release Tag and package.json Version Consistency
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

    # 检查标签和版本一致性
      - name: Check tag and package.json version
        run: |
          TAG_REF="${GITHUB_REF##*/}"
          echo "Current tag: $TAG_REF"
          PKG_VERSION=$(jq -r .version package.json)
          echo "package.json version: $PKG_VERSION"
          if [[ "$TAG_REF" != "v$PKG_VERSION" ]]; then
            echo "Tag ($TAG_REF) does not match package.json version (v$PKG_VERSION)."
            exit 1
          fi
          echo "Tag and package.json version are consistent."

  create-release-for-ios:
    needs: check_tag_version
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          save-if: false 

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Pnpm install and check
        run: |
          pnpm i

      - name: Init Tauri
        run: |
          pnpm tauri ios init
  
      - name: Build Tauri
        run: |
          pnpm tauri ios build

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          name: Spend What v${{ steps.package-version.outputs.current-version}}
          tag_name: v${{ steps.package-version.outputs.current-version}}
          files: |
            ./src-tauri/gen/android/app/build/outputs/apk/universal/release/spend-what_${{ steps.package-version.outputs.current-version}}.apk